### ISSUE TITLE
Get URAP students signed up for gb-mobile-interventions team

### ISSUE THREAD

**Issue by davclark** [glass-bead-labs/taichi-videos#1]
### GitHub

Please leave a comment below with your username!

If you don't have a github account yet, please make one! And don't forget to "request a discount" for 5 free private repos (for your own projects) [here](http://education.github.com).

Once you do have a github id, please post to the above issue, and I'll add you to the team so we can collaborate on code. Don't worry if you don't know how to use github yet - this will be part of the onboarding process. If you're eager to learn more now, check the help button at the top of this page!
### Vimeo

I'll also be uploading and sharing the videos with you on vimeo. So, please also make sure you sign up for an account there (and let me know if you use a different email address than the one I'm using here).
### Scheduling

In an ideal world, you all use google calendar to manage your time, and we'll use the "find a time" feature to schedule meetings. Let me know whether you do. If not, I will appoint one of the people who _doesn't_ use google calendar to manage meetings via when2meet (or similar).​
### Lab Website

Also, feel free to make a pull request [here](https://github.com/glass-bead-labs/bead.glass/blob/gh-pages/members.md), which will update [the lab members page](http://bead.glass/members).
### Learning contracts

Once you've signed up here, we'll start implementing learning contracts for this semester.

**Comment by arjunmehta94** [comment]
Hey Dav,

Thank you for having me on board! My github is linked to both by personal and student email accounts - arjunmehta94@gmail.com, arjunmehta94@berkeley.edu respectively. I just made a Vimeo on arjunmehta94@gmail.com.

In response to the Scheduling point, I do use Google Calendar.

**Comment by cecile-b** [comment]
Hi everyone! I do not use Google Calendar but I could do the whentomeet.

 Looking forward to this semester!

**Comment by davclark** [comment]
Don't forget to sign up to vimeo so you can see and work with the videos there @cecile-b!

**Comment by davclark** [comment]
And I'm still waiting on @arjunmehta94 to accept the invitation to our mobile-interventions github team...

**Comment by arjunmehta94** [comment]
Sorry the github join request went to my spam for some reason! Done.

On Fri, Feb 13, 2015 at 1:42 PM, Dav Clark notifications@github.com wrote:

> And I'm still waiting on @arjunmehta94 https://github.com/arjunmehta94
> to accept the invitation to our mobile-interventions github team...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/glass-bead-labs/taichi-videos/issues/1#issuecomment-74332077
> .

## 

Arjun Mehta
Electrical Engineering and Computer Sciences '17
University of California, Berkeley

**Comment by davclark** [comment]
I also _think_ I sent invites to both of you on my "Mobile Interventions" group on Vimeo - but I don't see either of you there yet. Let me know if you see that invite!

**Comment by arjunmehta94** [comment]
Hi Dav, I didn't receive any invite. Would you mind sending it again? My
vimeo is on arjunmehta94@gmail.com

**Comment by davclark** [comment]
Grrr... sent again! There doesn't appear to be a non-email based process.
So, if this doesn't work, I'll contact support.

D

**Comment by cecile-b** [comment]
At the moment I don't see it...

**Comment by cecile-b** [comment]
I see it but I can't open it - can you try sending it to my gmail account?

Cecile

**Comment by arjunmehta94** [comment]
Got it! Thanks!

**Comment by cecile-b** [comment]
I get the error "Sorry, this Group is private. You do not have permission to view this Group."

**Comment by davclark** [comment]
Let's just try and figure this one out next week... Thanks for your
efforts, though.

D
